# These are supported funding model platforms

# github: [alexleekt] # Uncomment and replace with your GitHub username if you want sponsorships
custom: ['https://github.com/sponsors/alexleekt']  # Replace with your actual sponsorship link
